In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
emails = pd.read_csv('emails.csv')

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
emails

,text,spam
0,Subject: naturally irresistible your corporate...,1
1,Subject: the stock trading gunslinger fanny i...,1
2,Subject: unbelievable new homes made easy im ...,1
3,Subject: 4 color printing special request add...,1
4,"Subject: do not have money , get software cds ...",1
...,...,...
5723,Subject: re : research and development charges...,0
5724,"Subject: re : receipts from visit jim , than...",0
5725,Subject: re : enron case study update wow ! a...,0
5726,"Subject: re : interest david , please , call...",0


In [6]:
cv = CountVectorizer()

In [7]:
emails_cv = cv.fit_transform(emails['text'])

In [8]:
cv.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzn', 'zzncacst', 'zzzz'], dtype=object)

In [9]:
print(emails_cv.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
x = emails_cv.toarray()

In [11]:
y = emails['spam'].values

In [12]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,shuffle=True)

In [16]:
from sklearn.naive_bayes import MultinomialNB , GaussianNB, BernoulliNB

In [17]:
clf = MultinomialNB()

In [18]:
clf.fit(x_train,y_train)

MultinomialNB()

In [19]:
y_pred = clf.predict(x_test)

In [20]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       850
           1       0.99      0.97      0.98       296

    accuracy                           0.99      1146
   macro avg       0.99      0.99      0.99      1146
weighted avg       0.99      0.99      0.99      1146



In [22]:
clf = GaussianNB()

In [23]:
clf.fit(x_train,y_train)

GaussianNB()

In [24]:
y_pred = clf.predict(x_test)

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       856
           1       0.95      0.88      0.91       290

    accuracy                           0.96      1146
   macro avg       0.96      0.93      0.94      1146
weighted avg       0.96      0.96      0.96      1146



In [26]:
clf = BernoulliNB()

In [27]:
clf.fit(x_train,y_train)

BernoulliNB()

In [28]:
y_pred = clf.predict(x_test)

In [29]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       859
           1       0.96      0.97      0.96       287

    accuracy                           0.98      1146
   macro avg       0.97      0.98      0.98      1146
weighted avg       0.98      0.98      0.98      1146

